/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class App {
    public String getGreeting() {
        return "Hello World! :)";
    }

    public static void main(String[] args) {
        WebDriver driver = new ChromeDriver();
        driver.get("https://faretek.dev");
        driver.quit();
        System.out.println(new App().getGreeting());
    }
}
